/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/gnx.glb 
Author: Losson (https://sketchfab.com/losson)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/buick-regal-gnx-1987-524dadfc588a4554892879dd8217d746
Title: Buick Regal GNX 1987
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'

export function GNX(props) {
  const { nodes, materials } = useGLTF('./models/gnx.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <lineSegments geometry={nodes.Object_2.geometry} material={materials.BACK} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.CAR_CHROME} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.CAR_PLASTIC} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.GLASS_LIGHT} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.GLASS_LIGHT_1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.GLASS_LIGHT_BACK} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.GLASS_LIGHT_BACK_2} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.GLASS_LIGHT_POVOROTNIC_2} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.RED_LIGHTS} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.RED_LIGHTS_2} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.RED_LIGHTS_3} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Truba} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.BACK} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.BACK} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.BACK} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.BREAK} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.BREAK} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.BREAK} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.BREAK} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Buick} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Buick} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Buick} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_37.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['CAR_.001']} />
        <mesh geometry={nodes.Object_43.geometry} material={materials['CAR_PLASTIC.002']} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['CAR_PLASTIC.002']} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['CAR_PLASTIC.002']} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.CHROME} />
        <mesh geometry={nodes.Object_57.geometry} material={materials.GLASS} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.GLASS_LIGHT_POVOROTNIC} />
        <mesh geometry={nodes.Object_59.geometry} material={materials.RUBBER_1} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.RUBBER_1} />
        <mesh geometry={nodes.Object_61.geometry} material={materials.RUBBER_1} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.RUBBER_1} />
        <lineSegments geometry={nodes.Object_63.geometry} material={materials.SUPPORT} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.SUPPORT} />
        <mesh geometry={nodes.Object_65.geometry} material={materials.SUPPORT} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.SUPPORT} />
        <mesh geometry={nodes.Object_67.geometry} material={materials.SUPPORT} />
        <lineSegments geometry={nodes.Object_68.geometry} material={materials['Tires.002']} />
        <mesh geometry={nodes.Object_69.geometry} material={materials['Tires.002']} />
        <mesh geometry={nodes.Object_70.geometry} material={materials['Tires.002']} />
        <mesh geometry={nodes.Object_71.geometry} material={materials['Tires.002']} />
        <mesh geometry={nodes.Object_72.geometry} material={materials['Tires.002']} />
        <mesh geometry={nodes.Object_73.geometry} material={materials['Tires.002']} />
        <mesh geometry={nodes.Object_74.geometry} material={materials['Tires.002']} />
        <mesh geometry={nodes.Object_75.geometry} material={materials['Tires.002']} />
        <mesh geometry={nodes.Object_76.geometry} material={materials['Tires.002']} />
      </group>
    </group>
  )
}

useGLTF.preload('./models/gnx.glb')
